api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    title: "LEV Agency Miziki"
    description: "This is the REST Api for the Miziki Application"
    version: 0.0.1

